# Generated by Django 3.1.2 on 2020-11-10 21:26

import auth_app.CustomUser
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_auto_20201103_2218'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', auth_app.CustomUser.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Please use another email for this user'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_app_customuser_related', to='auth_app.position'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_app_customuser_related', to='auth_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Please use another username'}, max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
